sudo: required
services:
  - docker

before_install:
  - docker build -t semiscone/travis -f Dockerfile.dev .

script:
  - docker run semiscone/travis npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "travis"
  env: "Travis-env"
  bucket_name: "elasticbeanstalk-us-west-1-022643302964"
  bucket_path: "travis"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

